module.exports = {
    MD_COLUMN_INDEX: 0,
    INC_COLUMN_INDEX: 1,
    AZI_COLUMN_INDEX: 2,
    TVD_COLUMN_INDEX: 3,
    NS_COLUMN_INDEX: 5,
    EW_COLUMN_INDEX: 6,
    VS_COLUMN_INDEX: 15,
    DLS_COLUMN_INDEX: 11,
    TOOLFACE_COLUMN_INDEX: 12,
    BUILDRATE_COLUMN_INDEX: 13,
    TURNRATE_COLUMN_INDEX: 14,
    COMMENTS_COLUMN_INDEX: 20,
};